### ISSUE TITLE
Add support for kmz

### ISSUE THREAD

**Issue by ajmas** [mapbox/togeojson#119]
It would be useful to add kmz support.

**Comment by tmcw** [comment]
Thanks for the suggestion. I've considered this in #88 and decided not to include KMZ support in toGeoJSON: it's a much more complex task to convert & properly display KMZ files, one that would be great for a different library but would go over the time budget I allot for toGeoJSON.

**Comment by ajmas** [comment]
The challenge is the support of embedded supporting files? I am just asking, in case I decide to look at creating a solution myself. Also, would you object to the name togeojson-kmz, if I do decide to embark on this?

**Comment by tmcw** [comment]
Go for it, I'd have no problem with that name. There are roughly 3 issues I think about re: KMZs:

* Since KMZ files are often generated by Google Earth, and Google Earth loves NetworkLinks, they often contain NetworkLinks. Those are really hard for toGeoJSON and other browser-capable parsers to handle because cross-domain requests are often blocked.
* You'll need a ZIP parser that runs reliably in a browser
* KMZ files often contain images and other resources that are referenced by the KML file. Displaying those embedded images etc in a browser isn't super simple because you would need to create blobs or data urls to embed them.

**Comment by ajmas** [comment]
Thanks. If I did this, based on those issues, I think I would target NodeJS first and then see the steps to bring it to the front-end.
