### ISSUE TITLE
Jsdom does not support nodejs anymore

### ISSUE THREAD

**Issue by BenSower** [mapbox/togeojson#71]
Starting from version 4, jsdom is not supporting nodejs anymore, meaning the nodejs example mentioned in the readme is not working anymore. 
The easiest fix for now would be a note saying that "you should use jsdom <= version 3". 
Since this is not a proper long term solution, I was wondering, if anyone knows a module similar to jsdom for parsing. If so, I could update the readme, if you want to.

**Comment by robhawkes** [comment]
I'm also keen to know what the long-term solution to this will be as the whole jsdom situation hasn't filled me with confidence – even the 3.x branch that uses Node.js will no longer be supported and updated in the future.

I've been looking at alternatives such as [htmlparser2](https://github.com/fb55/htmlparser2) but it implements a slightly custom DOM API – same methods but accessed separately with the DOM passed as an argument rather than via each DOM element.

**Comment by tmcw** [comment]
toGeoJSON is a DOM-based approach: the 'streaming way' is nice, but not the technique we use here.

The solution here is either that

* People use older versions of jsdom that support nodejs
* The melodramatic nodejs vs iojs drama blows over and jsdom supports node (since [they are starting to be friends again](https://github.com/nodejs/node/issues/1664))
* Fans of pragmatism fork jsdom into a compatible version

---

Anyway, the current solution of just using a support jsdom is perfectly fine for now.
