### ISSUE TITLE
Styles no longer work from Google maps output

### ISSUE THREAD

**Issue by p-somers** [mapbox/togeojson#72]
Not sure about other sources but Google maps at least has added the <StyleMap id="abc123"> tag, which has the id that the data nodes map to, instead of the <Style> tags having it. The style tags have "abc123-normal" and "abc123-highlight", which this module doesn't pick up on, so the styleUrl tag is not being set, and therefore style items are being ignored.

**Comment by friedbunny** [comment]
@p-somers submitted a pull request to fix this in #73.

**Comment by tmcw** [comment]
Closing; no test case was found and no standard exists.

**Comment by zallesov** [comment]
Came here 10 years after. WIth the same issue =)

**Comment by tmcw** [comment]
I'd accept a PR to this on the maintained fork at https://github.com/placemark/togeojson though I continue to be annoyed that Google is outputting a non-standardized variant that it could easily standardize because Google has sway in both the OGC KML spec as well as its independent documentation of the spec - this kind of arbitrariness on their part is really anti-web and anti-standards
