### ISSUE TITLE
Support for elevation and time?

### ISSUE THREAD

**Issue by ajmas** [mapbox/togeojson#85]
Would it be possible to add support for time? The current draft suggests the following:

https://tools.ietf.org/html/draft-butler-geojson-06#section-2.1.1

This would mean the format could be of the form [x,y,z,t], where:

   - if we have lon, lat, elevation, time: [lon, lat, elev, time]

For the exact time format, this could be handled a user definable function?

**Comment by ajmas** [comment]
Just got the latest code and see that both time and elevation are provided, with the time being in propertes.coordTimes. Is there any reason why this approach is used, rather than treating time as a dimension?

**Comment by tmcw** [comment]
See previously:

* https://github.com/mapbox/togeojson/issues/83
* https://github.com/mapbox/geojson-coordinate-properties

toGeoJSON already contains support for encoding time, elevation, and heartrate according to the coordinate-properties strawman spec. From [conversation on the spec mailing list](http://lists.geojson.org/htdig.cgi/geojson-geojson.org/2013-August/thread.html#821) as well as trying out various representations of the data, I came to the conclusion that this data should _not_ be stored within the coordinates array because of the lack of metadata as well as limited representation - time always as unix or javascript timestamps. A user-definable function with the in-spec restriction that the position would be "an array of numbers" means only really two possibilities - javascript microtime or unix timestamps.

I think that the current implementation, which places arrays of extra data alongside geometries rather than within them, is optimal.

**Comment by sgillies** [comment]
Fwiw, the IETF GeoJSON working group's next draft version will explicitly recommend that [x, y, z] positions *not* be extended: https://github.com/geojson/draft-geojson/blob/master/middle.mkd#position.

**Comment by gendronb** [comment]
Is the current implementation supposed to be in sync with Mapbox's `geojson-coordinate-properties` proposal (https://github.com/mapbox/geojson-coordinate-properties)? Time is still outputted as ISO dates in `properties.coordTimes` (instead of timestamps in `properties.coordinateProperties.times`.
