### ISSUE TITLE
Support KML compressed format. That it, KMZ

### ISSUE THREAD

**Issue by jcea** [mapbox/togeojson#88]
I have tons and tons of documents in KMZ format. This is a KML document in a ZIP file. It is a documented https://en.wikipedia.org/wiki/Keyhole_Markup_Language#Structure.

You can see an example of KMZ format in http://www.jcea.es/pics/italia2015/italia2015.kmz.

Could you possibly add support for this format in the library?. There are ZIP unpacking libraries available in javascript and I only need to support the bare minimum: a zip file with a single KML file inside.

I can't do this myself. My Javascript skills are laughable :-(

Thanks!.

**Comment by tmcw** [comment]
This would be great as a pre-processing tool that handled KMZ and its edges cases. Unfortunately many KMZ files are zip files of networklink files which networklink to other files and are generally very difficult to support, because they heavily use google extensions.

toGeoJSON's goal is achievable; supporting all variations is not. I'm going to stick with a promise I can keep and leave the KMZ task for anyone to grab.
